### ISSUE TITLE
Kapacitor 1.5.8 Release

### ISSUE THREAD

**Issue by psteinbachs** [influxdata/kapacitor#2407]
#### Complete When

- [x] [Big Panda Integration](https://github.com/influxdata/feature-requests/issues/165) lands
- [x] [Service Now Integration](https://github.com/influxdata/feature-requests/issues/176) lands 
- [x] Functionality exists for [setting the description of OpsGenie alerts](https://github.com/influxdata/feature-requests/issues/161)
- [x] Make sure Go version is >= 1.15.5, Covers at least CVE-2020-28362

**Comment by timhallinflux** [comment]
BigPanda: https://github.com/influxdata/kapacitor/pull/2414 
Service Now: https://github.com/influxdata/kapacitor/pull/2416

**Comment by docmerlin** [comment]
@timhallinflux `Service Now` made it into 1.5.7 on the kap side.  It still doesn't have Chronograf support, to my knowledge.

**Comment by timhallinflux** [comment]
it does not, but I can ask Bonitoo to add that...as they are maintaining that project.
