### ISSUE TITLE
Kapacitor 1.6.0 Release

### ISSUE THREAD

**Issue by psteinbachs** [influxdata/kapacitor#2482]
This epic tracks work scheduled for the Kapacitor 1.6 release.  It will be considered functionally complete when the following are implemented:

- [x] Zenoss Event Handler #2484 
- [x] queryflux node #2398
- [x] Flux tasks side-by-side #2533
- [x] A `to` function implementation

**Comment by timhallinflux** [comment]
https://github.com/influxdata/kapacitor/issues/2478

**Comment by docmerlin** [comment]
https://github.com/influxdata/kapacitor/issues/2527
